"""initial commit2

Revision ID: 1dbd4c39d5b2
Revises: 2dc8894fe1ee
Create Date: 2023-12-04 22:48:13.524825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dbd4c39d5b2'
down_revision: Union[str, None] = '2dc8894fe1ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('interviewer_id', sa.Integer(), nullable=True))
    op.drop_constraint('surveys_interviewers_id_fkey', 'surveys', type_='foreignkey')
    op.create_foreign_key(None, 'surveys', 'interviewers', ['interviewer_id'], ['id'])
    op.drop_column('surveys', 'interviewers_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('interviewers_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'surveys', type_='foreignkey')
    op.create_foreign_key('surveys_interviewers_id_fkey', 'surveys', 'interviewers', ['interviewers_id'], ['id'])
    op.drop_column('surveys', 'interviewer_id')
    # ### end Alembic commands ###
