"""add survey models

Revision ID: f1c3892874f1
Revises: 8f70431b532a
Create Date: 2023-12-05 15:52:22.287428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c3892874f1'
down_revision: Union[str, None] = '8f70431b532a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.Enum('single_chose', 'multiple_chose', 'text', name='questiontype'), nullable=True),
    sa.Column('question_answers', sa.Text(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    # ### end Alembic commands ###
